name: closet_connect_final
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  flutter_svg_provider: ^1.0.3
  flutter_rating_bar: ^4.0.0
  flutter_staggered_grid_view: ^0.4.1
  intl: ^0.17.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Castoro
      fonts: 
        - asset: assets/fonts/CastoroRegular.ttf
          weight: 400
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoRomanBold.ttf
          weight: 700
        - asset: assets/fonts/RobotoMedium.ttf
          weight: 500
        - asset: assets/fonts/RobotoBold.ttf
          weight: 700
        - asset: assets/fonts/RobotoRomanLight.ttf
          weight: 300
        - asset: assets/fonts/RobotoLight.ttf
          weight: 300
        - asset: assets/fonts/RobotoRomanMedium.ttf
          weight: 500
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
    - family: Nunito Sans
      fonts: 
        - asset: assets/fonts/NunitoSansBold.ttf
          weight: 700
        - asset: assets/fonts/NunitoSansLight.ttf
          weight: 300
    - family: Noto Sans
      fonts: 
        - asset: assets/fonts/NotoSans.ttf
          weight: 400
        - asset: assets/fonts/NotoSansBold.ttf
          weight: 700
    - family: Open Sans
      fonts: 
        - asset: assets/fonts/OpenSansRegular.ttf
          weight: 400
        - asset: assets/fonts/OpenSansSemiBold.ttf
          weight: 600
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/MontserratBold.ttf
          weight: 700
        - asset: assets/fonts/MontserratRegular.ttf
          weight: 400
    - family: Nunito
      fonts: 
        - asset: assets/fonts/NunitoRegular.ttf
          weight: 400
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
