import '../overview_closet_screen/widgets/grid_item_widget.dart';import 'package:closet_connect_final/core/app_export.dart';import 'package:closet_connect_final/presentation/address_page/address_page.dart';import 'package:closet_connect_final/widgets/app_bar/appbar_iconbutton.dart';import 'package:closet_connect_final/widgets/app_bar/appbar_image.dart';import 'package:closet_connect_final/widgets/app_bar/appbar_subtitle_5.dart';import 'package:closet_connect_final/widgets/app_bar/custom_app_bar.dart';import 'package:closet_connect_final/widgets/custom_bottom_bar.dart';import 'package:closet_connect_final/widgets/custom_floating_button.dart';import 'package:flutter/material.dart';import 'package:flutter_staggered_grid_view/flutter_staggered_grid_view.dart';
// ignore_for_file: must_be_immutable
class OverviewClosetScreen extends StatelessWidget {GlobalKey<NavigatorState> navigatorKey = GlobalKey();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: ColorConstant.whiteA700, appBar: CustomAppBar(height: getVerticalSize(56.00), leadingWidth: 63, leading: AppbarIconbutton(svgPath: ImageConstant.imgArrowleftWhiteA700, margin: getMargin(left: 33, top: 12, bottom: 14), onTap: () => onTapArrowleft22(context)), centerTitle: true, title: AppbarSubtitle5(text: "Closet"), actions: [AppbarImage(height: getSize(45.00), width: getSize(45.00), svgPath: ImageConstant.imgFloatingicon, margin: getMargin(left: 19, top: 5, right: 19, bottom: 5), onTap: () => onTapFloatingicon(context))]), body: Padding(padding: getPadding(top: 22), child: StaggeredGridView.countBuilder(shrinkWrap: true, primary: false, crossAxisCount: 4, crossAxisSpacing: getHorizontalSize(26.00), mainAxisSpacing: getHorizontalSize(26.00), staggeredTileBuilder: (index) {return StaggeredTile.fit(2);}, itemCount: 4, itemBuilder: (context, index) {return GridItemWidget();})), bottomNavigationBar: CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}), floatingActionButton: CustomFloatingButton(height: 56, width: 59, child: CustomImageView(svgPath: ImageConstant.imgSearchWhiteA700, height: getVerticalSize(28.00), width: getHorizontalSize(29.50))))); } 
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Home: return AppRoutes.addressPage; case BottomBarEnum.Computer: return "/"; case BottomBarEnum.Mail: return "/"; case BottomBarEnum.User: return "/"; default: return "/";} } 
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.addressPage: return AddressPage(); default: return DefaultWidget();} } 
onTapArrowleft22(BuildContext context) { Navigator.pop(context); } 
onTapFloatingicon(BuildContext context) { Navigator.pushNamed(context, AppRoutes.addClothesScreen); } 
 }
