import 'package:closet_connect_final/core/app_export.dart';import 'package:closet_connect_final/presentation/address_page/address_page.dart';import 'package:closet_connect_final/widgets/app_bar/appbar_iconbutton.dart';import 'package:closet_connect_final/widgets/app_bar/appbar_subtitle_5.dart';import 'package:closet_connect_final/widgets/app_bar/custom_app_bar.dart';import 'package:closet_connect_final/widgets/custom_bottom_bar.dart';import 'package:closet_connect_final/widgets/custom_button.dart';import 'package:closet_connect_final/widgets/custom_floating_button.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class CartEmptyScreen extends StatelessWidget {GlobalKey<NavigatorState> navigatorKey = GlobalKey();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: ColorConstant.whiteA700, appBar: CustomAppBar(height: getVerticalSize(56.00), leadingWidth: 67, leading: AppbarIconbutton(svgPath: ImageConstant.imgArrowleftWhiteA700, margin: getMargin(left: 37, top: 13, bottom: 13), onTap: () => onTapArrowleft16(context)), centerTitle: true, title: AppbarSubtitle5(text: "Cart")), body: Container(width: size.width, child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(svgPath: ImageConstant.imgGroupDeepOrange100, height: getVerticalSize(107.00), width: getHorizontalSize(113.00), alignment: Alignment.centerLeft, margin: getMargin(left: 39, top: 6)), Padding(padding: getPadding(top: 39), child: Text("No orders yet", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtRobotoBold20.copyWith(height: getVerticalSize(1.24)))), Container(width: getHorizontalSize(170.00), margin: getMargin(top: 15), child: Text("Hit the orange button down\nbelow to Create an order", maxLines: null, textAlign: TextAlign.center, style: AppStyle.txtRobotoRegular14Gray900.copyWith(height: getVerticalSize(1.28)))), CustomButton(height: 58, width: 224, text: "Start ordering", margin: getMargin(top: 79), shape: ButtonShape.RoundedBorder15)])), bottomNavigationBar: CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}), floatingActionButton: CustomFloatingButton(height: 56, width: 59, child: CustomImageView(svgPath: ImageConstant.imgSearchWhiteA700, height: getVerticalSize(28.00), width: getHorizontalSize(29.50))))); } 
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Home: return AppRoutes.addressPage; case BottomBarEnum.Computer: return "/"; case BottomBarEnum.Mail: return "/"; case BottomBarEnum.User: return "/"; default: return "/";} } 
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.addressPage: return AddressPage(); default: return DefaultWidget();} } 
onTapArrowleft16(BuildContext context) { Navigator.pop(context); } 
 }
